name: Build Ultra Micro APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk/26.1.10909125
          key: ${{ runner.os }}-ndk-26.1.10909125
      
      - name: Build Process
        run: |
          if [ ! -d "/usr/local/lib/android/sdk/ndk/26.1.10909125" ]; then
            sdkmanager "ndk;26.1.10909125"
          fi
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          make build
          
      - name: Upload Signed APK Only
        uses: actions/upload-artifact@v4
        with:
          name: Odfiz-Micro-App
          path: "*-signed.apk" # Hanya ambil file yang sudah di-sign
